SmallWebsite/SmallWebsite/urls.py
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

from SmallWebsite import settings
from . import views

urlpatterns = [
    path('home/',views.home, name='home'),

    path('message/',include('message.urls')),
    path('person/',include('person.urls')),
    path('user/',include('user.urls')),

    path('admin/', admin.site.urls),
    path('loadmore/', views.loadmore,name='loadmore'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SmallWebsite/person/urls.py
from django.urls import path
from . import views

app_name = 'person'

urlpatterns = [

    path('myVIP/', views.myVIP, name='myVIP'),
    path('charge/', views.charge, name='charge'),
    path('myJF/',views.myJF, name='myJF'),
    path('exchange/', views.exchange, name='exchange'),
    path('myFB/', views.myFB, name='myFB'),
    path('notify/',views.notify, name='notify'),

    path('profile/',views.profile, name='profile'),
    path('changepwd/',views.changepwd, name='changepwd'),
    path('resetpwd/', views.resetpwd, name='resetpwd'),
    path('logout/', views.logout, name='logout'),
]

SmallWebsite/user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [

    #也可以使用django内置的用户来搞
    # path('logintest/',auth_views.LoginView.as_view(template_name='inner_login.html'), name='logintest'),

    # 用户注册
    path('register/',views.u_register, name='register'),
    path('register/',views.u_register, name='registertest'),

    # 用户登录
    path('login/',views.u_login, name='logintest'),
    path('login/',views.u_login, name='login'),

    # 忘记密码
    path('forget/',views.u_forget, name='forget'),

    # 重置密码
    path('reset/',views.u_reset, name='reset'),
]

SmallWebsite/person/models.py
from django.db import models

# Create your models here.
from user.models import UserRegister
from message.models import new_messages


# 会员购买记录
class Money_Charge_Record(models.Model):
    code = models.CharField(max_length=20)
    charge_money = models.IntegerField()
    charge_time = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(UserRegister,on_delete=models.CASCADE,related_name="spend_money_user")


# 我写的积分账单
class Exchange_Record(models.Model):
    # 记录用户干了啥
    detail = models.CharField(max_length=100)
    #  记录积分增加还是减少了多少，有符号
    get_or_cost = models.IntegerField()
    exchange_time = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(UserRegister,on_delete=models.CASCADE,related_query_name='exchg_user')


# 积分账单记录
class Charge(models.Model):
    intg_num = models.IntegerField()
    intg_detail = models.CharField(max_length=100)
    use_time = models.TimeField(auto_now=True)


class ChargeRecord(models.Model):
    charge_kind = models.IntegerField()
    charge_time = models.TimeField(auto_now=True)


# 消息通知
class NotifyRec(models.Model):
    comment = models.CharField(max_length=500)
    comment_time = models.TimeField(auto_now=True)
    comment_user = models.ForeignKey(UserRegister, on_delete=models.CASCADE, related_name='comment_user')
    commented_message = models.ForeignKey(new_messages, on_delete=models.CASCADE, related_name='commented_message')

SmallWebsite/person/views.py
import datetime

from django.contrib.auth.hashers import make_password
from django.shortcuts import render
from django.http import HttpResponse
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger

from user.models import UserRegister
from user.views import my_login_required
from message.models import new_messages
from person.models import *

import random,time


@my_login_required
def myVIP(request):
    mobile_num = request.session['username']
    login_user = UserRegister.objects.get(account_number=mobile_num)
    # 充钱分页
    money_charges = Money_Charge_Record.objects.filter(user=login_user)
    paginator = Paginator(money_charges,3)
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        contacts = paginator.page(1)
    except EmptyPage:
        contacts = paginator.page(paginator.num_pages)
    return render(request,'person/myVIP.html',{'login_flag':True,'user':login_user,'contacts':contacts})


@my_login_required
def myJF(request):
    mobile_num = request.session['username']
    login_user = UserRegister.objects.get(account_number=mobile_num)
    # 积分分页
    exchanges = Exchange_Record.objects.filter(user=login_user)
    paginator = Paginator(exchanges,3)
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        contacts = paginator.page(1)
    except EmptyPage:
        contacts = paginator.page(paginator.num_pages)
    return render(request, 'person/myJF.html',{'login_flag':True,'user':login_user,'contacts':contacts})


@my_login_required
def myFB(request):
    mobile_num = request.session['username']
    user = UserRegister.objects.get(account_number=mobile_num)
    messages = new_messages.objects.filter(pub_user=user)
    # 闪开，我要开始分页了
    paginator = Paginator(messages, 3)
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        # 如果请求不是整数，返回第一页
        contacts = paginator.page(1)
    except EmptyPage:
        # 如果请求的页数不在合法的预算书范围内，返回结果的最后一页
        contacts = paginator.page(paginator.num_pages)
    return render(request,'person/myFB.html',{'login_flag':True,'contacts':contacts,'user':user,'messages':messages})


@my_login_required
def notify(request):
    mobile_num = request.session['username']
    user = UserRegister.objects.get(account_number=mobile_num)
    notifies = NotifyRec.objects.filter(comment_user=user)
    return render(request,'person/notify.html',{'login_flag':True,'notifies':notifies,'user':user})


@my_login_required
def profile(request):
    mobile_num = request.session['username']
    user = UserRegister.objects.get(account_number=mobile_num)
    if request.method == 'POST':
        user.mini_name = request.POST['nickname']
        user.account_number = request.POST['mobile_num']
        user.save()
        return HttpResponse("个人资料修改成功")
    else:
        return render(request,'person/profile.html',{'login_flag':True,'user':user})


@my_login_required
def changepwd(request):
    mobile_num = request.session['username']
    user = UserRegister.objects.get(account_number=mobile_num)
    if request.method == 'POST':
        u_mobile = request.POST['u_mobile']
        return render(request,'person/resetpwd.html',{'login_flag':True,'u_mobile':u_mobile,'user':user})
    else:
        return render(request,'person/changepwd.html',{'login_flag':True,'user':user})


@my_login_required
def resetpwd(request):
    mobile_num = request.session['username']
    user = UserRegister.objects.get(account_number=mobile_num)
    if request.method == 'POST':
        u_mobile = request.POST['u_mobile']
        resetpwduser = UserRegister.objects.get(account_number=u_mobile)
        if request.POST['ur_pwd'] != request.POST['ur_cfmpwd']:
            return render(request,'resetpwd.html',{'error':'两次密码不一致'})
        else:
            resetpwduser.password = make_password(request.POST['ur_pwd'])
            resetpwduser.save()
            return HttpResponse("密码修改成功。")
    else:
        return render(request, 'person/resetpwd.html',{'login_flag':True,'user':user})


@my_login_required
def logout(request):
    del request.session['username']
    return render(request,'person/logout.html')


# 这个充值，，这里应该有支付宝或者微信的接口，然后支付的。
# 我们就在这里面计算应该花多少钱吧——不管积分
@my_login_required
def charge(request):
    mobile_num = request.session['username']
    user = UserRegister.objects.get(account_number=mobile_num)
    charge_record = Money_Charge_Record()
    charge_record.user = user
    pubed_counts = new_messages.objects.filter(pub_user=user).filter(new_pub__year=datetime.datetime.now().year).filter(
        new_pub__month=datetime.datetime.now().month).count()
    if request.method == 'GET':
        return render(request,'person/charge.html', {'login_flag':True})
    else:
        if request.POST['chg_type'] == '1':
            if user.level > 0:
                error = "请勿重复充值"
                return render(request,'person/charge.html',{'login_flag':True,'error':error})
            # 假装支付宝里面钱够。
            if True:
                time_stamp = str(int(time.time()))
                ran_strr = ""
                for i in range(6):
                    ch = chr(random.randrange(ord('0'),ord('9')+1))
                    ran_strr += ch
                charge_record.code = ran_strr+time_stamp
                charge_record.charge_money = spend_money = 2000
                user.times = 2 - pubed_counts
                if user.times < 0:
                    user.times = 0
                user.level = 1
                user.save()
                charge_record.save()
                return HttpResponse("VIP1充值成功,花了{}大洋".format(spend_money))
            else:
                error = "钱不够"
                return render(request,'person/charge.html',{'login_flag':True,'error':error})
        elif request.POST['chg_type'] == '2':
            if user.level > 1:
                error = "请勿重复充值"
                return render(request,'person/charge.html',{'login_flag':True,'error':error})
            if user.level == 1:
                remain_money = 2000
            else:
                remain_money = 0
            if True:
                time_stamp = str(int(time.time()))
                ran_strr = ""
                for i in range(6):
                    ch = chr(random.randrange(ord('0'), ord('9') + 1))
                    ran_strr += ch
                charge_record.code = ran_strr + time_stamp
                charge_record.charge_money = spend_money = 5000 - remain_money
                user.level = 2
                # 剩余发布次数等于5 - 用户本月发布的新闻数量
                user.times = 5 - pubed_counts
                if user.times < 0:
                    user.times = 0
                user.save()
                charge_record.save()
                return HttpResponse("VIP2充值成功，花了{}大洋".format(spend_money))
            else:
                error = '钱不够'
                return render(request,'person/charge.html',{'login_flag':True,'error':error})
        elif request.POST['chg_type'] == '3':
            if user.level > 2:
                error = "请勿重复充值"
                return render(request,'person/charge.html',{'login_flag':True,'error':error})
            if user.level == 1:
                remain_money = 2000
            elif user.level == 2:
                remain_money = 5000
            else:
                remain_money = 0
            if True:
                time_stamp = str(int(time.time()))
                ran_strr = ""
                for i in range(6):
                    ch = chr(random.randrange(ord('0'), ord('9') + 1))
                    ran_strr += ch
                charge_record.code = ran_strr + time_stamp
                charge_record.charge_money = spend_money = 10000 - remain_money
                user.level = 3
                # 剩余发布次数等于5 - 用户本月发布的新闻数量
                user.times = 10 - pubed_counts
                if user.times < 0:
                    user.times = 0
                user.save()
                charge_record.save()
                return HttpResponse("VIP3充值成功,花了{}大洋".format(spend_money))
            else:
                error = '钱不够'
                return render(request,'person/charge.html',{'login_flag':True,'error':error})

        return HttpResponse("选择的VIP等级是:{},用户原有的积分:{}".format(request.POST['ex_type'],user.scores))



@my_login_required
def exchange(request):
    mobile_num = request.session['username']
    user = UserRegister.objects.get(account_number=mobile_num)
    exRecord = Exchange_Record()
    exRecord.user = user
    pubed_counts = new_messages.objects.filter(pub_user=user).filter(new_pub__year=datetime.datetime.now().year).filter(
        new_pub__month=datetime.datetime.now().month).count()
    if request.method == 'POST':
        if request.POST['ex_type'] == '1':
            if user.level > 0:
                error = "请勿重复充值"
                return render(request,'person/exchange.html',{'login_flag':True,'error':error})
            if user.scores - 20000 > 0:
                user.scores -= 20000
                exRecord.detail = "积分兑换VIP1"
                exRecord.get_or_cost = -20000
                user.times = 2 - pubed_counts
                if user.times < 0:
                    user.times = 0
                user.level = 1
                user.save()
                exRecord.save()
                return HttpResponse("VIP1充值成功")
            else:
                error = "积分不足"
                return render(request,'person/exchange.html',{'login_flag':True,'error':error})
        elif request.POST['ex_type'] == '2':
            if user.level > 1:
                error = "请勿重复充值"
                return render(request,'person/exchange.html',{'login_flag':True,'error':error})
            if user.level == 1:
                remain = 20000
            else:
                remain = 0
            if user.scores+remain - 50000 > 0:

SmallWebsite/templates/person/changepwd.html
{% extends 'personalbase.html' %}

{% block personal_content %}
    <div style="padding-left: 30px;padding-top: 30px;">
        <div>修改密码</div>
        <div style="width: 420px;height: 400px;position: absolute;left: 200px;top:100px;">
            <form action="{% url 'person:changepwd' %}" method="post">
                {% csrf_token %}
                <input type="text" name="u_mobile" placeholder="请输入手机号"  style="border-style: none;width: 418px;color:#888888;height: 40px;outline: none">
                <hr style="margin-top: 2px;">
                <input type="text" name="verify_code" placeholder="请输入验证码" style="border-style: none;width: 240px;color:#888888;height: 40px;outline: none;margin-top: -5px;">
                <div  name="getverify_code_btn" style="float: right;width: 140px;height: 42px;background-color:#1992EF;color:white;font-size: 16px;border: none;text-align: center;line-height: 42px;">获取验证码</div>
                <hr style="margin-top: 2px;width: 240px;">
                <input type="submit" name="login_btn" id="next_step" value="下一步" style="width: 420px;height: 50px;outline: none;background-color:#1992EF;border-radius: 4px;color:white;font-size: 16px;margin-top: 10px;border: none">
            </form>
        </div>
    </div>
{% endblock %}

SmallWebsite/templates/person/charge.html
{% extends 'base.html' %}

{% block content %}
    <div style="border-left:4px solid black;border-top:1px solid #EFEFEF;border-right:1px solid #EFEFEF;border-bottom:1px solid #EFEFEF;width: 1152px;height: 52px;position: absolute;top:9px;left: 264px;line-height: 52px;">支付</div>
    <div style="border:1px solid #EFEFEF;width: 1152px;height: 872px;position: absolute;top: 67px;left: 264px;">
    <!-- 在这里实现充值功能 -->
        <form action="{% url 'person:charge' %}" method="post">
            {% csrf_token %}
            <input type="radio" checked name="chg_type" value=1 id="vip_one"><label for="vip_one">VIP1</label>
            <input type="radio" name="chg_type" value=2 id="vip_two"><label for="vip_two">VIP2</label>
            <input type="radio" name="chg_type" value=3 id="vip_three"><label for="vip_three">VIP3</label>

            <input type="submit">
        </form>
        <div>{{ error }}</div>
    </div>
{% endblock %}

SmallWebsite/templates/person/exchange.html
{% extends 'base.html' %}

{% block content %}
    <div style="border-left:4px solid black;border-top:1px solid #EFEFEF;border-right:1px solid #EFEFEF;border-bottom:1px solid #EFEFEF;width: 1152px;height: 52px;position: absolute;top:9px;left: 264px;line-height: 52px;">积分兑换会员</div>
    <div style="border:1px solid #EFEFEF;width: 1152px;height: 872px;position: absolute;top: 67px;left: 264px;">
    <!-- 在这里实现充值功能 -->
        <div style="width: 1100px;height: 76px;background-color: #F9FAFD;margin: 25px;line-height: 76px;">支付积分:</div>
        <strong>选择购买方式</strong>
        <!--
        <div style="width: 210px;height: 92px;background-color: red;position: absolute;"></div>
        <div style="width: 210px;height: 92px;background-color: blue;position: absolute;left: 250px;"></div>
        <div style="width: 210px;height: 92px;background-color: yellow;position: absolute;left: 500px;"></div>
        -->
        <form action="{% url 'person:exchange' %}" method="post">
            {% csrf_token %}
            <input type="radio" checked name="ex_type" value=1 id="vip_one"><label for="vip_one">VIP1</label>
            <input type="radio" name="ex_type" value=2 id="vip_two"><label for="vip_two">VIP2</label>
            <input type="radio" name="ex_type" value=3 id="vip_three"><label for="vip_three">VIP3</label>

            <input type="submit">
        </form>
        <div>{{ error }}</div>
    </div>
{% endblock %}

SmallWebsite/templates/person/logout.html
{% extends 'base.html' %}

{% block content %}
    退出登录
{% endblock %}

SmallWebsite/templates/person/myFB.html
{% extends 'personalbase.html' %}

{% block personal_content %}
<div style="padding-left: 30px;padding-top: 30px;">
        <div>我的发布</div>
        <div style="">
        <ul style="height: 52px" id="main_nav">
            <li>全部</li>
            <li>待审核</li>
            <li>审核通过</li>
            <li>审核未通过</li>
        </ul>
        </div>
<hr>
    <div id="publish_content">
{#        {% for message in messages %}#}
        <!--
            <div style="background-color: red;width: 782px;height: 177px;margin: 10px;">{{ message.new_title }}</div>
         -->
{#        {% endfor %}#}
        {% for contact in contacts %}
            {# 每个"contact"都是一个Contact模型对象。 #}
            {{ contact.new_title|upper }}<br />
        {% endfor %}
        
        {#  分页标签的HTML代码 #}
        <div class="pagination">
            <span class="step-links">
                {% if contacts.has_previous %}
                    <a href="?page={{ contacts.previous_page_number }}" style="color: black;">上一页</a>
                {% endif %}

                <span class="current">
                    Page{{ contacts.number }} of {{ contacts.paginator.num_pages }}.
                </span>

                {% if contacts.has_next %}
                    <a href="?page={{ contacts.next_page_number }}" style="color: black;">下一页</a>
                {% endif %}
            </span>
        </div>
    </div>
</div>
{% endblock %}

SmallWebsite/templates/person/myJF.html
{% extends 'personalbase.html' %}

{% block personal_content %}
<div style="padding-left: 30px;padding-top: 30px;">
        <div>我的积分</div>
        <div>当前剩余积分:<span>{{ user.scores }}</span><a href="{% url 'person:exchange' %}" style="background-color: #1992EF">兑换会员</a></div>
        <hr>
        <div>积分说明</div>
        <div>这里是积分说明，可以从数据库里面取出来</div>
        <hr>
        <div>积分账单</div>
        <div>
             {% for contact in contacts %}
            {# 每个"contact"都是一个Contact模型对象。 #}
                 <pre style="font-size: 20px;">
{{ contact.detail }}        {{ contact.get_or_cost }}          {{ contact.exchange_time }}<br />
                 </pre>
        {% endfor %}

        {#  分页标签的HTML代码 #}
        <div class="pagination">
            <span class="step-links">
                {% if contacts.has_previous %}
                    <a href="?page={{ contacts.previous_page_number }}" style="color: black;">上一页</a>
                {% endif %}

                <span class="current">
                    Page{{ contacts.number }} of {{ contacts.paginator.num_pages }}.
                </span>

                {% if contacts.has_next %}
                    <a href="?page={{ contacts.next_page_number }}" style="color: black;">下一页</a>
                {% endif %}
            </span>
        </div>
        </div>
</div>
{% endblock %}

SmallWebsite/templates/person/myVIP.html
{% extends 'personalbase.html' %}

{% block personal_content %}
    <div style="padding-left: 30px;padding-top: 30px;">
        <div>我的会员</div>
        <div>当前<span>VIP</span> <span>{{ user.level }}</span>级,本月剩余文章发布次数:<span>{{ user.times }}</span>次
            <a href="{% url 'person:charge' %}" style="background-color: #1992EF;">续费/升级</a>
        </div>
        <hr>
        <div>会员等级说明</div>
        <div style="height: 150px;" id="VIP_Info">
            <div style="position: absolute">VIP1</div>
            <div style="position: absolute">VIP2</div>
            <div style="position: absolute">VIP3</div>
        </div>
        <hr>
        <div>购买记录</div>
        <div>
            {% for contact in contacts %}
            {# 每个"contact"都是一个Contact模型对象。 #}
                 <pre style="font-size: 20px;">
{{ contact.code }}        {{ contact.charge_money }}          {{ contact.charge_time }}<br />
                 </pre>
        {% endfor %}

        {#  分页标签的HTML代码 #}
        <div class="pagination">
            <span class="step-links">
                {% if contacts.has_previous %}
                    <a href="?page={{ contacts.previous_page_number }}" style="color: black;">上一页</a>
                {% endif %}

                <span class="current">
                    Page{{ contacts.number }} of {{ contacts.paginator.num_pages }}.
                </span>

                {% if contacts.has_next %}
                    <a href="?page={{ contacts.next_page_number }}" style="color: black;">下一页</a>
                {% endif %}
            </span>
        </div>
        </div>
    </div>
{% endblock %}

SmallWebsite/templates/person/notify.html
{% extends 'personalbase.html' %}

{% block personal_content %}
    <div style="padding-left: 30px;padding-top: 30px;">
        <div>消息通知</div>
        <hr>
        {% for notify in notifies %}
            <div>{{ notify.comment }}</div>
        {% endfor %}
    </div>
{% endblock %}

SmallWebsite/templates/person/profile.html
{% extends 'personalbase.html' %}

{% block personal_content %}
    <div style="padding-left: 30px;padding-top: 30px;">
        <div>个人资料</div>
        <form action="{% url 'person:profile' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="portrait">头像:</label><input type="file" id="portrait" name="portrait">
            <br>
            <label for="nickname">昵称:</label><input type="text" id="nickname" name="nickname">
            <br>
            <label for="mobile_num">手机号:</label><input type="text" id="mobile_num" name="mobile_num">
            <br>
            <input type="submit" value="更改">
        </form>
    </div>
{% endblock %}

SmallWebsite/templates/person/resetpwd.html
{% extends 'personalbase.html' %}

{% block personal_content %}
        <div style="padding-left: 30px;padding-top: 30px;">
        <div>修改密码</div>
        <div style="width: 420px;height: 400px;position: absolute;left: 200px;top:100px;">
            <form action="{% url 'person:resetpwd' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="username" value="{{ username }}">
                <input type="password" name="ur_pwd" placeholder="请输入6位以上的密码" style="width: 418px;height: 40px;border-style: none;outline: none;">
                <hr style="margin-top: 2px;">
                <input type="password" name="ur_cfmpwd" placeholder="请再次输入密码" style="width: 418px;height: 40px;border-style: none;outline: none;">
                <hr style="margin-top: 2px;">

                <input type="submit" name="login_btn" value="修改" style="width: 420px;height: 50px;outline: none;background-color:#1992EF;border-radius: 4px;color:white;font-size: 16px;margin-top: 10px;border: none">
            </form>
            <div>{{ error }}</div>
        </div>
    </div>
{% endblock %}