SmallWebsite/SmallWebsite/urls.py
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

from SmallWebsite import settings
from . import views

urlpatterns = [
    path('home/',views.home, name='home'),

    path('message/',include('message.urls')),
    path('person/',include('person.urls')),
    path('user/',include('user.urls')),

    path('admin/', admin.site.urls),
    path('loadmore/', views.loadmore,name='loadmore'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SmallWebsite/message/urls.py
from django.urls import path
from . import views

app_name = 'message'

urlpatterns = [
    path('',views.test,name='test'),
    path('fb/', views.fb,name='fb'),
    path('detail/<kind>/<int:article_id>', views.showdetail, name='detail'),
]

SmallWebsite/person/urls.py
from django.urls import path
from . import views

app_name = 'person'

urlpatterns = [

    path('myVIP/', views.myVIP, name='myVIP'),
    path('charge/', views.charge, name='charge'),
    path('myJF/',views.myJF, name='myJF'),
    path('exchange/', views.exchange, name='exchange'),
    path('myFB/', views.myFB, name='myFB'),
    path('notify/',views.notify, name='notify'),

    path('profile/',views.profile, name='profile'),
    path('changepwd/',views.changepwd, name='changepwd'),
    path('resetpwd/', views.resetpwd, name='resetpwd'),
    path('logout/', views.logout, name='logout'),
]

SmallWebsite/user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [

    #也可以使用django内置的用户来搞
    # path('logintest/',auth_views.LoginView.as_view(template_name='inner_login.html'), name='logintest'),

    # 用户注册
    path('register/',views.u_register, name='register'),
    path('register/',views.u_register, name='registertest'),

    # 用户登录
    path('login/',views.u_login, name='logintest'),
    path('login/',views.u_login, name='login'),

    # 忘记密码
    path('forget/',views.u_forget, name='forget'),

    # 重置密码
    path('reset/',views.u_reset, name='reset'),
]

SmallWebsite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'mycss/mainpage.css' %}">
    <script src="{% static 'js/jquery.js' %}"></script>
    <style type="text/css">
        *{
            padding: 0;
            margin: 0;
        }
        #base_nav a{
            text-decoration: none;
            color: white;
        }
        #base a:hover, a:visited, a:link, a:active{
            text-decoration: none;
            color: white;
        }
        /*
        li{
            list-style: none;
            float: left;
            width: 80px;
            height: 52px;
            text-align: center;
            line-height: 52px;
        }
        */
        #main_nav li{
            list-style: none;
            float: left;
            width: 80px;
            height: 52px;
            text-align: center;
            line-height: 52px;
        }
    </style>
</head>
<body>
        <div style="background-color: #2C323E;height: 70px;width: 100%">
            <a href="{% url 'home' %}"><img src="{% static 'images/logo.png' %}" style="width:141px;height:31px;margin-top: 19px;margin-left: 271px;" ></a>

            <!--未登录 -->
                {% block user_status %}
                    {% if  login_flag %}
                        <div style="width: 78px;height: 28px;border: 1px solid white;border-radius: 28px;text-align: center;line-height: 28px;position: absolute;right: 535px;top:18px;"><a href="{% url 'message:fb' %}">发布内容</a></div>
                        <div style="position: absolute;width: 34px;height: 34px;background-color: yellow;right: 480px;border-radius: 100%;top: 13px;">
                            <a href="{% url 'person:myVIP' %}">test</a>
                        </div>
                    {% else %}
                        <div style="position:absolute;left: 1340px;top:24px;">
                            <a href="{% url 'user:login' %}">登录</a>
                                        <span style="color: white;padding:5px;">|</span>
                            <a href="{% url 'user:register' %}">注册</a>
                        </div>
                    {% endif %}
                {% endblock %}
            <!--  下面的是登录成功后显示的页面:
            <div style="width: 34px;height: 34px;margin-top: 17px;margin-right: 270px;background-color: red;float:right">发布内容</div>
            <div style="width: 78px;height: 28px;;margin-top: 20px;margin-right: 28px;background-color:yellow;float: right"></div>
            -->
        </div>
        <div style="position: relative">
            {% block content %}
            {% endblock %}
        </div>
</body>
</html>

SmallWebsite/templates/forgetpwd.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div style="border-left:4px solid black;border-top:1px solid #EFEFEF;border-right:1px solid #EFEFEF;border-bottom:1px solid #EFEFEF;width: 1152px;height: 52px;position: absolute;top:9px;left: 264px;">
        <!-- 样式待调整 -->
        <div style="float: left;line-height: 52px;margin-left: 28px;font-size: 16px;"><strong>忘记密码</strong></div>
    </div>
    <div style="border:1px solid #EFEFEF;width: 1152px;height: 872px;position: absolute;top: 67px;left: 264px;">
        <div style="width: 420px;height: 215px;position: absolute;left: 365px;top:120px;text-align: left    ">
            <form action="{% url 'user:forget' %}" method="post">
                {% csrf_token %}
                <input type="text" name="u_mobile" placeholder="请输入手机号"  style="border-style: none;width: 418px;color:#888888;height: 40px;outline: none">
                <hr style="margin-top: 2px;">
                <!--
                <input type="text" name="mob_num" placeholder="请输入手机号"  style="border-style: none;width: 418px;color:#888888;height: 40px;outline: none">
                -->
                <hr style="margin-top: 2px;">
                <input type="text" name="verify_code" placeholder="请输入验证码" style="border-style: none;width: 240px;color:#888888;height: 40px;outline: none;margin-top: -5px;">
                <div  name="getverify_code_btn" style="float: right;width: 140px;height: 42px;background-color:#1992EF;color:white;font-size: 16px;border: none;text-align: center;line-height: 42px;">获取验证码</div>
                <!--
                <img src="/user/getvcode"  id="image"><br>
                验证码:
                <input type="text" placeholder="请输入验证码" name="vcode"><br>
                <input type="file" name="uicon"><br>
                -->

                <!--
                验证码:
                <img src="/get_validcode_img/" alt="">
                -->
                <hr style="margin-top: 2px;width: 240px;">
                <input type="submit" name="login_btn" id="next_step" value="下一步" style="width: 420px;height: 50px;outline: none;background-color:#1992EF;border-radius: 4px;color:white;font-size: 16px;margin-top: 10px;border: none">
            </form>
            <!--  这儿是错误信息 -->
            <div>{{ error }}</div>
        </div>
    </div>
        <script src="{% static 'js/jquery.js' %}">
    </script>
    <script type="text/javascript">
$(function(){
    $("#next_step").click(function () {
        var username = $("#u_mobile").val();
        var validcode = $("#validcode").val();

        $.ajax({
            url: "/forget/",
            type: "POST",
            data : {"username":username, "validcode":validcode},
            headers: {"X-CSRFToken": $.cookie("csrftoken")},  //配置csrftoken
            success: function (data) {
                console.log(data);
                var response = JSON.parse(data);
                if (response["is_login"]){
                    self.location.href = ("/index/")
                }else{
                    $(".error").html(response["error_msg"]).css("color","red")
                }
            }
        })
    })
})
    </script>
{% endblock %}

SmallWebsite/templates/inner_login.html
{% extends "base.html" %}


{% block content %}
    {% load static %}
    <div style="border-left:4px solid black;border-top:1px solid #EFEFEF;border-right:1px solid #EFEFEF;border-bottom:1px solid #EFEFEF;width: 1152px;height: 52px;position: absolute;top:9px;left: 264px;">
        <!-- 样式未调整 -->
        <div style="float: left;line-height: 52px;margin-left: 28px;font-size: 16px;"><strong>欢迎登录</strong></div>
        <div style="float: right;line-height: 52px;margin-right: 22px;font-size: 16px;"><strong>还没有账号?<a href="{% url 'user:register' %}" style="color: #1992EF">立即注册</a></strong></div>
    </div>
    <div style="border:1px solid #EFEFEF;width: 1152px;height: 872px;position: absolute;top: 67px;left: 264px;">
        <div style="width: 420px;height: 215px;position: absolute;left: 365px;top:120px;text-align: center    ">
            <form action="{% url 'user:login' %}" method="post" formnovalidate id="loginform">
                {% csrf_token %}
                <!--
                <input type="text" name="username" autofocus required id="id_username" placeholder="请输入用户名"  style="border-style: none;width: 418px;color:#888888;height: 40px;outline: none">
                -->
                <input type="text" name="mobile" autofocus required placeholder="请输入手机号" style="border-style: none;width: 418px;color:#888888;height: 40px;outline: none">
                <hr style="margin-top: 2px;">
                <!--
                <input type="password" name="u_pwd" placeholder="请输入密码" style="border-style: none;width: 418px;color:#888888;height: 40px;outline: none;margin-top: -5px;">
                -->

                <input type="password" name="password" autofocus required placeholder="请输入密码"  style="border-style: none;width: 418px;color:#888888;height: 40px;outline: none">

{#                {{ form.password }}#}
                <hr style="margin-top: 2px;">
                <div style="height: 20px;margin-top: -10px;">
                    <div style="float: left"><label><input id="remember" type="checkbox">记住密码</label></div>
                    <div style="float: right"><a href="{% url 'user:forget' %}" style="color: #888888;"><strong>忘记密码？</strong></a>  </div>
                </div>
                <input type="submit" name="login_btn" value="登录" style="width: 420px;height: 50px;outline: none;background-color:#1992EF;border-radius: 4px;color:white;font-size: 16px;margin-top: 20px;border: none">
            </form>

            <div style="margin: auto">{{ ERROR_INFO }}</div>
        </div>
    </div>
    <script type="text/javascript">

        window.onload = function(){
            var oForm = document.getElementById('loginform');
            var oUser = document.getElementById('id_mobile');
            var oPswd = document.getElementById('id_password');
            var oRemember = document.getElementById('remember');
            if(getCookie('id_mobile') && getCookie('id_password')){
                oUser.value = getCookie('id_mobile');
                oPswd.value = getCookie('id_password');
                oRemember.checked = true;
            }
            //复选框状态发生改变时，如果未勾选则清除cookie
            oRemember.onchange = function(){
                if(!this.checked){
                    delCookie('id_mobile');
                    delCookie('id_password')
                }
            };
            //表单提交事件触发时，如果复选框是勾选状态则保存cookie
            oForm.onsubmit = function(){
                if(remeber.checked()) {
                    setCookie('id_mobile', oUser.value, 7);
                    setCookie('id_password', oPswd.value, 7)
                }
            };
        };
            //设置cookie
            function setCookie(name,value,day){
                var date = new Date();
                date.setDate(date.getDate() + day);
                document.cookie = name + '=' + value + ';expires=' + date;
            };
            //获取cookie
            function getCookie(name) {
                var reg = RegExp(name+'(=[^;]+)');
                var arr = document.cookie.match(reg);
                if(arr){
                    return arr[1];
                }else{
                    return '';
                }
            };
            //删除cookie
            function delCookie(name){
                setCookie(name,null,-1);
            };
    </script>
{% endblock %}

SmallWebsite/templates/inner_register.html
{% extends "base.html" %}


{% block content %}
    <div style="border-left:4px solid black;border-top:1px solid #EFEFEF;border-right:1px solid #EFEFEF;border-bottom:1px solid #EFEFEF;width: 1152px;height: 52px;position: absolute;top:9px;left: 264px;">
        <!-- 样式待调整 -->
        <div style="float: left;line-height: 52px;margin-left: 28px;font-size: 16px;"><strong>欢迎注册</strong></div>
        <div style="float: right;line-height: 52px;margin-right: 22px;font-size: 16px;"><strong>已有账号?<a href="{% url 'user:login' %}" style="color: #1992EF">立即登录</a></strong></div>
    </div>
    <div style="border:1px solid #EFEFEF;width: 1152px;height: 872px;position: absolute;top: 67px;left: 264px;">
        <div style="width: 420px;height: 215px;position: absolute;left: 365px;top:120px;text-align: left    ">
            <form action="{% url 'user:register' %}" method="post">
                {% csrf_token %}
                <input type="text" name="u_mobile" placeholder="请输入手机号"  style="border-style: none;width: 418px;color:#888888;height: 40px;outline: none">
                <!-- 用户名不能全部是数字，所以……-->
                <hr style="margin-top: 2px;">
                <!--
                <input type="text" name="mob_num" placeholder="请输入手机号"  style="border-style: none;width: 418px;color:#888888;height: 40px;outline: none">
                -->
                <hr style="margin-top: 2px;">
                <input type="text" name="verify_code" placeholder="请输入验证码" style="border-style: none;width: 240px;color:#888888;height: 40px;outline: none;margin-top: -5px;">
                <div  name="getverify_code_btn" style="float: right;width: 140px;height: 42px;background-color:#1992EF;color:white;font-size: 16px;border: none;text-align: center;line-height: 42px;">获取验证码</div>
                <hr style="margin-top: 2px;width: 240px;">
                <input type="password" name="ur_pwd" placeholder="请输入6位以上的密码" style="width: 418px;height: 40px;border-style: none;outline: none;">
                <hr style="margin-top: 2px;">
                <input type="password" name="ur_cfmpwd" placeholder="请再次输入密码" style="width: 418px;height: 40px;border-style: none;outline: none;">
                <hr style="margin-top: 2px;">

                <input type="submit" name="login_btn" value="注册" style="width: 420px;height: 50px;outline: none;background-color:#1992EF;border-radius: 4px;color:white;font-size: 16px;margin-top: 10px;border: none">
            </form>

            <!--  这儿是错误信息 -->
            <div>{{ error }}</div>
        </div>
    </div>
{% endblock %}

SmallWebsite/templates/main.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <!--轮播图-->
    <div style="background-color: black;width: 520px;height: 300px;margin-top: 10px;margin-left: 265px;position: absolute;border-radius: 4px;">
        <div id="box" class="carousel slide" data-ride="carousel">

        </div>
    </div>
    <!-- 两张图-->
    <div style="background-color: red;width: 246px;height: 142px;left:799px;top:10px;position: absolute;border-radius: 4px;"></div>
    <div style="background-color: yellow;width: 246px;height: 142px;left:799px;top:168px;position: absolute;border-radius: 4px;"></div>

    <!-- 导航栏  回头将这几个栏目用表读出来-->
    <div style="border-left:4px solid black;border-top:1px solid #EFEFEF;border-right:1px solid #EFEFEF;border-bottom:1px solid #EFEFEF;width:782px;height: 52px;left:264px;top:320px;position: absolute">
    <ul style="height: 52px" id="main_nav">
        <li id="show_news">新闻</li>
        <li id="show_policy">政策</li>
        <li id="show_hq">行情</li>
        <li id="show_tech">技术</li>
    </ul>
    </div>


    <!-- 快讯和热门新闻  没有写完 -->
    <div style="border-top:4px solid black;border-left:1px solid #EFEFEF;border-right:1px solid #EFEFEF;border-bottom:1px solid #EFEFEF;width: 332px;height: 722px;position: absolute;left: 1084px;top:9px;">
    <div style="text-align: center;top: 18px;left:146.5px;position: absolute;font-size: 18px;color:#2C323E;"><strong>快讯</strong></div>
    <div id="kx_list">
        {% for kx in kxs %}
            <a href="{{ kx.get_url_path }}"><div>{{ kx.new_title }}</div></a>
        {% endfor %}
    </div>
    <div style="border:1px solid #1992EF;width: 108px;height: 32px;left:112px;bottom:21px;position: absolute;border-radius: 6px;line-height: 32px;text-align: center;color:#1992EF">查看更多资讯</div>
    </div>

    <div style="border-top:4px solid black;border-left:1px solid #EFEFEF;border-right:1px solid #EFEFEF;border-bottom:1px solid #EFEFEF;width: 332px;height: 696px;position: absolute;left: 1084px;top:759px;">
    <div style="text-align: center;top: 18px;left:127px;position: absolute;font-size: 18px;color:#2C323E;">
        <strong>热门新闻</strong>
    </div>
    </div>

    <!-- 这里和上面的li使用jQuery搞出来效果 -->
    <div id="article">
        <!-- 新闻 -->
        <div style="border:1px solid #EFEFEF;width: 782px;height:1239px;position: absolute;top:391px;left: 264px" id="news" class="article_content">
            {% for new in news %}
                <div style="border-bottom: 1px solid #EFEFEF;height: 177px;">
                    <!-- 这里调整目录的显示效果，左边一张图片，右边是文章内容等 -->

                    <a href="{{ new.get_url_path }}"><div style="padding: 19px;">{{ new.new_title }}</div></a>
                </div>
            {% endfor %}
        </div>
        <!-- 政策 -->
        <div style="border:1px solid #EFEFEF;width: 782px;height:1239px;position: absolute;top:391px;left: 264px" id="policy" class="article_content">
            {% for policy in policies %}
                <div style="border-bottom: 1px solid #EFEFEF;height: 177px;">
                    <!-- 调整效果 -->
                    <a href="{{ policy.get_url_path }}"><div style="padding: 19px;">{{ policy.new_title }}</div></a>
                </div>
            {% endfor %}
        </div>
        <!-- 行情 -->
        <div style="border:1px solid #EFEFEF;width: 782px;height:1239px;position: absolute;top:391px;left: 264px" id="hq" class="article_content">
            {% for hq in hqs %}
                <div style="border-bottom: 1px solid #EFEFEF;height: 177px;">
                    <!-- 调整效果 -->
                    <a href="{{ hq.get_url_path }}"><div style="padding: 19px;">{{ hq.new_title }}</div></a>
                </div>
            {% endfor %}
        </div>
        <!-- 技术 -->
        <div style="border:1px solid #EFEFEF;width: 782px;height:1239px;position: absolute;top:391px;left: 264px" id="tech" class="article_content">
            {% for tech in techs %}
                <div style="border-bottom: 1px solid #EFEFEF;height: 177px;">
                    <a href="{{ tech.get_url_path }}"><div style="padding: 19px;">{{ tech.new_title }}</div></a>
                </div>
            {% endfor %}
        </div>
    </div>


    <div style="border:1px solid #EFEFEF;width: 782px;height: 88px;position: absolute;top:1630px;left: 264px;text-align: center;color: #1992EF;">
        <div style="border:1px solid #1992EF;width: 90px;height: 32px;left:346px;top:28px;position: absolute;border-radius: 6px;line-height: 32px;">加载更多</div>
    </div>

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/dist/carousel.js' %}"></script>
    <script type="text/javascript">
var i = 2
function loadmore(){
    //得到当前url
    var url = window.location.pathname,
    url = url.substring(url.lastIndexOf('/') + 1, url.length);

    if (url.includes("search")){}else{
        var reg = new RegExp("");
        url = url.replace(reg,"loadmore");
        var xmlhttp = new XMLHttpRequest();
        xmlhttp.onreadystatechange = function(){
            if(xmlhttp.readyState == 4 && xmlhttp.status == 200){
                $('.list').append(xmlhttp.responseText);
                var idclass  = $('.detail');
                idclass.each(function(){
                    var content = $(this).text();
                    $(this).html(content);
                });
            }
        }
        xmlhttp.open("GET",url + "?page=" + i,true);
        i = i + 1;
        xmlhttp.send(null);
    }
}
    </script>
    <script>
    $(document).scroll(function () {
        if ($(document).scrollTop() >= $(document).height() - $(window).height()){
            loadmore();
        }
    });
    </script>
    <script type="text/javascript">
    //首先让新闻政策等内容清空
$("#article .article_content div").css("display","none");

//然后只显示新闻的内容
$("#news div").css("display","block");
$("#news").css("z-index",999)

//鼠标点击
$("#main_nav li").click(function(){
	//隐藏全部
	$("#article .article_content div").css("display","none");
	//下面的内容可以封装成一个函数
	//显示对应的内容
	if ($(this).index()==0) {
		$("#article .article_content div").css("display","none");
		$("#article .article_content").css('z-index',0)
		$("#news div").css("display","block");
		$("#news").css("z-index",999);
	}
	if ($(this).index()==1) {
		$("#article .article_content div").css("display","none");
		$("#article .article_content").css('z-index',0)
		$("#policy div").css("display","block");
		$("#policy").css("z-index",999);
	}
	if ($(this).index()==2) {
		$("#article .article_content div").css("display","none");
		$("#article .article_content").css('z-index',0)
		$("#hq div").css("display","block");
		$("#hq").css("z-index",999);
	}
	if ($(this).index()==3) {
		$("#article .article_content div").css("display","none");
		$("#article .article_content").css('z-index',0)
		$("#tech div").css("display","block");
		$("#tech").css("z-index",999);
	}
});
    </script>
{% endblock %}

SmallWebsite/templates/personalbase.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    <!-- Left -->
    <div style="width: 300px; height: 1100px; position: absolute;left:265px;top:15px;">
        <!-- Top -->
        <div style="width: 300px; height: 216px; background-color: #2c323E;">
            <div style="background-color: red; width:72px;height:72px;position:absolute;top:19px;left:114px;border-radius: 100%"></div>
            <span style="color: white;width: 84px; height: 20px;font-size: 20px;position:absolute; top: 102px;left:108px;">{{ user.mini_name }}</span>
            <img src="{% static 'images/vip.png' %}" alt="" style="position:absolute;top:104px;right: 86px;">
            <div style="width:300px;height:50px;position:absolute;top:146px;">
                <div style="width:150px;height: 50px;text-align: center;color:white;float:left;">剩余积分
                    <p>{{ user.scores }}</p>
                </div>
                <div style="width: 150px;height: 50px;text-align: center;float:right;border-left: 1px solid #FFFFFF;color:white;">剩余发布次数
                    <p>{{ user.times }}</p>
                </div>
            </div>
        </div>
        <!-- Down -->
        <div style="border-left:1px #EFEFEF solid;border-right:1px #EFEFEF solid;border-bottom:1px #EFEFEF solid;width:300px;height: 845px;position: absolute;top:216px;">
            <div style=" height: 60px;line-height: 60px;padding-left: 22px;font-size: 18px;color: #2C323E">
                <img src="{% static 'images/my_vip.png' %}" style="padding-right: 7px;"><a style="color:black;" href="{% url 'person:myVIP' %}">我的会员</a></div>
            <div style=" height: 60px;line-height: 60px;padding-left: 22px;font-size: 18px;color: #2C323E">
                <img src="{% static 'images/my_jf.png' %}" style="padding-right: 7px;"><a style="color:black;" href="{% url 'person:myJF' %}">我的积分</a></div>
            <div style=" height: 60px;line-height: 60px;padding-left: 22px;font-size: 18px;color: #2C323E">
                <img src="{% static 'images/post_n.png' %}" style="padding-right: 7px;"><a style="color:black;" href="{% url 'person:myFB' %}">我的发布</a></div>
            <div style=" height: 60px;line-height: 60px;padding-left: 22px;font-size: 18px;color: #2C323E">
                <img src="{% static 'images/xxx_n.png' %}" style="padding-right: 7px;"><a style="color:black;" href="{% url 'person:notify' %}">消息通知</a></div>

            <div class="dropdown" style="height: 60px;">
                <div data-toggle="dropdown" style="height: 60px;line-height:60px;padding-left: 22px;font-size: 18px;color: #2C323E" >
                    <img src="{% static 'images/sz.png' %}" style="padding-right: 7px;">设置<i class="caret"></i></div>
                <div class="dropdown-menu" style="border:none;box-shadow: none;margin-left: 35px;" id="settings_menu">
                    <div><a href="{% url 'person:profile' %}"  style="color: black">个人资料</a> </div>
                    <div><a href="{% url 'person:changepwd' %}" style="color: black">修改密码</a></div>
                    <div><a href="{% url 'person:logout' %}" style="color: black">退出登录</a></div>
                </div>
            </div>
        </div>
    </div>
    <!-- Right -->
    <div style="width: 830px;height: 1060px;position:absolute;top: 15px;left:585px;border:1px solid #EFEFEF">
        {% block personal_content %}
        {% endblock %}
    </div>
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
{% endblock %}

SmallWebsite/templates/resetpwd.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <div style="border-left:4px solid black;border-top:1px solid #EFEFEF;border-right:1px solid #EFEFEF;border-bottom:1px solid #EFEFEF;width: 1152px;height: 52px;position: absolute;top:9px;left: 264px;">
        <!-- 样式待调整 -->
        <div style="float: left;line-height: 52px;margin-left: 28px;font-size: 16px;"><strong>修改密码</strong></div>
        <div style="float: right;line-height: 52px;margin-right: 22px;font-size: 16px;"><strong>已有账号?<a href="{% url 'user:login' %}" style="color: #1992EF">立即登录</a></strong></div>
    </div>
    <div style="border:1px solid #EFEFEF;width: 1152px;height: 872px;position: absolute;top: 67px;left: 264px;">
        <div style="width: 420px;height: 215px;position: absolute;left: 365px;top:120px;text-align: left    ">
            <form action="{% url 'user:reset' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="username" value="{{ username }}">
                <input type="password" name="ur_pwd" placeholder="请输入6位以上的密码" style="width: 418px;height: 40px;border-style: none;outline: none;">
                <hr style="margin-top: 2px;">
                <input type="password" name="ur_cfmpwd" placeholder="请再次输入密码" style="width: 418px;height: 40px;border-style: none;outline: none;">
                <hr style="margin-top: 2px;">

                <input type="submit" name="login_btn" value="修改" style="width: 420px;height: 50px;outline: none;background-color:#1992EF;border-radius: 4px;color:white;font-size: 16px;margin-top: 10px;border: none">
            </form>

            <!--  这儿是错误信息 -->
            <div>{{ error }}</div>
        </div>
    </div>

{% endblock %}